workflows:
  android-workflow:
    name: Build Android APK
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter clean
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-spruslan96@gmail.com
