workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        ANDROID_NDK_HOME: /usr/local/share/android-sdk/ndk/25.1.8937393
        ANDROID_NDK_ROOT: /usr/local/share/android-sdk/ndk/25.1.8937393
        PATH: /usr/local/share/android-sdk/cmake/3.22.1/bin:$PATH
    scripts:
      - name: Flutter doctor
        script: flutter doctor -v

      - name: Check NDK & CMake
        script: |
          echo ">>> Checking NDK and CMake..."
          echo "NDK path: $ANDROID_NDK_HOME"
          cmake --version
          $ANDROID_NDK_HOME/ndk-build --version || echo "ndk-build not found!"

      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release --verbose

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
