workflows:
  android-build:
    name: Android ARM64 Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release --target-platform android-arm64
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
