workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        ANDROID_SDK_ROOT: /usr/local/share/android-sdk
      cocoapods: default
    scripts:
      - name: Install specific NDK and CMake
        script: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;23.1.7779620" "cmake;3.18.1"
          export ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/23.1.7779620
          export PATH=$ANDROID_NDK:$PATH
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --target-platform android-arm64
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
