workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      android:
        ndk: 25.1.8937393
        cmake: 3.22.1
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK (Release)
        script: flutter build apk --release --target-platform android-arm64
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
