workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        FLUTTER_CHANNEL: stable
      cocoapods: default
    scripts:
      - name: Install Android SDK & NDK
        script: |
          yes | sdkmanager "cmake;3.18.1" "ndk;23.1.7779620"
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
