workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      android:
        ndk: 23.1.7779620
        cmake: 3.18.1
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
